---
- hosts: controller
  remote_user: g3n3zyp
  vars_files:
    - vars/default.yml
    - vars/user.yml
  tasks:

    - name: Create "/mnt/disk4Gv/local/k3s-controller" directory
      file:
        path: "/mnt/disk4Gv/local/k3s-controller"
        state: directory
        mode: 0755

    - name: Copy "docker-compose.yml" to "/mnt/disk4Gv/local/k3s-controller/" directory (if not exists)
      copy:
        src: ../k3s-controller/docker-compose.yml
        dest: /mnt/disk4Gv/local/k3s-controller/docker-compose.yml
        force: no
        mode: 0644

    - name: Pull services defined in docker-compose.yml
      command: docker-compose -f /mnt/disk4Gv/local/k3s-controller/docker-compose.yml pull

    - name: Run services defined in docker-compose.yml
      command: docker-compose -f /mnt/disk4Gv/local/k3s-controller/docker-compose.yml up -d
