apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-sh
  namespace: unifi
immutable: false  # Indicates that the ConfigMap can be modified
data:
  create_db.js: |
    db.createUser({
      user: "unifi",
      pwd: "unifi",
      roles: [
        {
        role: 'readWrite',
        db: "unifi"
        },
        {
        role: 'readWrite',
        db: "unifi_stat"
        }
      ]
    })