apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cadvisor-metrics-binding
subjects:
  - kind: ServiceAccount
    name: cadvisor
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cadvisor-metrics-reader
  apiGroup: rbac.authorization.k8s.io
