kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-ha
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
parameters:
  numberOfReplicas: "3"
  volumeBindingMode: Immediate
  staleReplicaTimeout: "30" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
#  mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
#  diskSelector: "ssd,fast"
#  nodeSelector: "storage,fast"
#  recurringJobSelector: '[
#   {
#     "name":"snap",
#     "isGroup":true,
#   },
#   {
#     "name":"backup",
#     "isGroup":false,
#   }
#  ]'
