# Enabling prometheus metrics and access logs
# Enable access log
logs:
  access:
    enabled: true
    format: json
# This is translated to traefik parameters
# "--metrics.prometheus=true"
# "--accesslog"
# "--accesslog.format=json"
  
# Print access log to file instead of stdout
additionalArguments:
  - "--accesslog.filepath=/data/access.log"
  - "--metrics.prometheus=true"
deployment:
  # Adding access logs sidecar
  additionalContainers:
    - name: stream-accesslog
      image: busybox
      args:
      - /bin/sh
      - -c
      - tail -n+1 -F /data/access.log
      - --serversTransport.insecureSkipVerify=true
      imagePullPolicy: Always
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /data
        name: data
service:
  spec:
    # Set load balancer external IP
    loadBalancerIP: 10.0.51.100

providers:
  # Enable cross namespace references
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  # Enable published service
  kubernetesIngress:
    publishedService:
      enabled: true