apiVersion: v1
kind: Service
metadata:
  namespace: ha
  name: mosquitto
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  type: NodePort
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 31883
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-01-vol01
  namespace: ha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ha
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
        volumeMounts:
        - mountPath: /mosquitto/data
          name: mqtt-01-volume
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-password
          mountPath: /mosquitto/config/password.txt
          subPath: password.txt
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"                   
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
      hostNetwork: true
      volumes:
      - name: mqtt-01-volume
        persistentVolumeClaim:
          claimName: mqtt-01-vol01
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
          defaultMode: 448
      - name: mosquitto-password
        configMap:
          name: mosquitto-password
          defaultMode: 0777