apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: mosquitto
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  type: NodePort
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 31883
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-mqtt-local-volume
  namespace: home-assistant
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mosquitto"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home-assistant
  name: gfs-mqtt-volume-claim
  labels:
    app: mosquitto
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
        volumeMounts:
        - mountPath: /mosquitto/data
          name: gfs-mqtt-volume
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-password
          mountPath: /mosquitto/config/password.txt
          subPath: password.txt
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
      hostNetwork: true
      volumes:
      - name: gfs-mqtt-volume
        persistentVolumeClaim:
          claimName: gfs-mqtt-volume-claim
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
          defaultMode: 448
      - name: mosquitto-password
        configMap:
          name: mosquitto-password
          defaultMode: 0777