# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: home-assistant
spec:
  selector:
    app: home-assistant
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
  # type: ClusterIP
  # ports:
  # - name: http
  #   protocol: TCP
  #   port: 80
  #   targetPort: 8123
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-home-assistant
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: ha.48340.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - ha.48340.xyz
      secretName: longhorn-http-tls
  ingressClassName: traefik
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: gfs-ha-local-volume
#   namespace: home-assistant
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/home-assistant" # path to directory
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: gfs-ha-volume-claim
#   labels:
#     app: home-assistant
#   namespace: home-assistant
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce #  must be the same as PersistentVolume
#   resources:
#     requests:
#       storage: 8Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-ha-01-volume-claim
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: home-assistant
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      initContainers:
      - name: mk-directory
        image: busybox:1.35
        command: ['sh', '-c', 'sleep 5 && echo "creating dir" && mkdir -p /config/automations && mkdir -p /config/scenes && touch /config/scenes.yaml &&  touch /config/automations.yaml && touch /config/customize.yaml && mkdir -p /config/scripts' ]
        volumeMounts:
        - mountPath: /config
          name: lh-ha-01-volume
      containers:
      - name: bluez
        image: ghcr.io/mysticrenji/bluez-service:v1.0.0
        securityContext:
          privileged: true
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2024.10.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "1024Mi"
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: lh-ha-01-volume
        - mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          name:  ha-configuration-cm
        # - mountPath: /config/automations/automations-lights-cm.yaml
        #   subPath: automations-lights-cm.yaml
        #   name: ha-automations-lights-cm
        - mountPath: /config/scenes/scenes-cm.yaml
          subPath: scenes-cm.yaml
          name: ha-scenes-cm
        # - mountPath: /config/scenes/scripts_k8s.yaml
        #   subPath: scripts_k8s.yaml
        #   name: configmap-file           
        # - mountPath: /config/customize.yaml
        #   subPath: customize.yaml
        #   name: lh-ha-01-volume
        - mountPath: /media
          name: lh-ha-01-volume
        securityContext:
          privileged: true
      hostNetwork: true
      volumes:
      - name: lh-ha-01-volume
        persistentVolumeClaim:
          claimName: lh-ha-01-volume-claim
      - name: media-volume
        hostPath:
          path: /tmp/media
      - name: ha-configuration-cm
        configMap:
          name: ha-configuration-cm
      - name: ha-automations-lights-cm
        configMap:
          name: ha-automations-lights-cm
      - name: ha-scenes-cm
        configMap:
          name: ha-scenes-cm
