---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ha-configuration-cm
  namespace: ha
data:
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    scene manual: !include_dir_merge_list scenes/
    scene ui: !include scenes.yaml
    # My own handmade automations
    automation manual: !include_dir_merge_list automations/
    # Automations I create in the UI
    automation ui: !include automations.yaml
    # scripts
    script manual: !include_dir_merge_list scripts/
    # scripts I create in the UI
    script ui: !include scripts.yaml     
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    homeassistant:
      customize: !include customize.yaml
    influxdb:
      api_version: 2
      ssl: false
      host: 10.0.0.103
      port: 8086
      token: -wVPsmk6flrZaNuIJ1ieqfQ7F0iLtzFj-8MMxckXaellrY5neu3GLpA1eJPJTJ2wgX0e9_pldM_-BHvXZnvKvA==
      organization: gampnet
      bucket: ha
      tags:
        source: HA
      tags_attributes:
        - friendly_name
      default_measurement: units
      include:
        entities:
          - weather.forecast_dom
          - sensor.pompa_temperatura_zewnetrzna
          - sensor.sensor_klimatu_01_bme680_temperatura
          - sensor.temp_01_temperature
          - sensor.temp_01_pressure
          - sensor.temp_01_humidity
          - sensor.temp_01_battery
          - sensor.temp_02_temperature
          - sensor.temp_02_pressure
          - sensor.temp_02_humidity
          - sensor.temp_02_battery
          - sensor.temp_03_temperature
          - sensor.temp_03_pressure
          - sensor.temp_03_humidity
          - sensor.temp_03_battery
          - sensor.temp_04_temperature
          - sensor.temp_04_pressure
          - sensor.temp_04_humidity
          - sensor.temp_04_battery
          - binary_sensor.pracujoncy

