# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  namespace: ha
  name: home-assistant
spec:
  selector:
    app: home-assistant
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
  # type: ClusterIP
  # ports:
  # - name: http
  #   protocol: TCP
  #   port: 80
  #   targetPort: 8123
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-home-assistant
  namespace: ha
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: ha.48340.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - ha.48340.xyz
      secretName: longhorn-http-tls
  ingressClassName: traefik
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: gfs-ha-local-volume
#   namespace: ha
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/home-assistant" # path to directory
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: gfs-ha-volume-claim
#   labels:
#     app: home-assistant
#   namespace: ha
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce #  must be the same as PersistentVolume
#   resources:
#     requests:
#       storage: 8Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: ha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-media
  namespace: ha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi         
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ha
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      initContainers:
      - name: mk-directory
        image: busybox:1.35
        command: ['sh', '-c', 'sleep 5 && echo "creating dir" && mkdir -p /config/automations && mkdir -p /config/scenes && touch /config/scenes.yaml &&  touch /config/automations.yaml && touch /config/customize.yaml && mkdir -p /config/scripts && touch /config/scripts.yaml && mkdir -p /config/sensors && touch /config/sensors.yaml' ]
        volumeMounts:
        - mountPath: /config
          name: ha-vol01
      containers:
      - name: bluez
        image: ghcr.io/mysticrenji/bluez-service:v1.0.0
        securityContext:
          privileged: true
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2024.12.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          # limits:
          #   memory: "768Mi"
          #   cpu: "500m"                  
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: ha-vol01
        - mountPath: /media
          name: media-volume
        - mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          name:  ha-configuration-cm
        - mountPath: /config/scenes/scenes-cm.yaml
          subPath: scenes-cm.yaml
          name: ha-scenes-cm
        - mountPath: /config/sensors/sensors-cm.yaml
          subPath: sensors-cm.yaml
          name: ha-sensors-cm          
        - mountPath: /config/automations/automations-pcg13-cm.yaml
          subPath: automations-pcg13-cm.yaml
          name: ha-automations-pcg13-cm              
        - mountPath: /.dockerenv
          name: volume-dockerenv
        securityContext:
          privileged: true
      hostNetwork: true
      volumes:
      - name: ha-vol01
        persistentVolumeClaim:
          claimName: home-assistant-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: ha-media
      - name: ha-configuration-cm
        configMap:
          name: ha-configuration-cm
      - name: ha-automations-lights-cm
        configMap:
          name: ha-automations-lights-cm
      - name: ha-automations-pcg13-cm
        configMap:
          name: ha-automations-pcg13-cm
      - name: ha-scenes-cm
        configMap:
          name: ha-scenes-cm
      - name: ha-sensors-cm
        configMap:
          name: ha-sensors-cm          
      - name: volume-dockerenv
        emptyDir: {}
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchLabels:
      #           app: ha
      #       topologyKey: kubernetes.io/hostname
