# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: home-assistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-ha-local-volume
  namespace: home-assistant
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/home-assistant" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gfs-ha-volume-claim
  labels:
    app: home-assistant
  namespace: home-assistant
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: bluez
        image: ghcr.io/mysticrenji/bluez-service:v1.0.0
        securityContext:
          privileged: true
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: gfs-ha-volume
        - mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          name:  configmap-file
        - mountPath: /config/automations.yaml
          subPath: automations.yaml
          name: configmap-file
        - mountPath: /config/customize.yaml
          subPath: customize.yaml
          name: gfs-ha-volume
        - mountPath: /media
          name: gfs-ha-volume          
        # - mountPath: /run/dbus
        #   name: d-bus
        #   readOnly: true
        #- mountPath: /dev/ttyACM0
        #  name: zigbee
        #  subPath: ttyACM0
        #- mountPath: /dev/video0
        #  name: cam
        securityContext:
          privileged: true
      hostNetwork: true
      volumes:
      - name: gfs-ha-volume
        persistentVolumeClaim:
          claimName: gfs-ha-volume-claim
      - name: media-volume
        hostPath:
          path: /tmp/media
      # - name: config_yml
      #   hostPath:
      #     path: "config/configuration"

      - name: configmap-file
        configMap:
          name: home-assistant-configmap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
  namespace: home-assistant
data:
  known_devices.yaml: |
  automations.yaml: |-
    - id: '1713609938281'
      alias: Światło_Serwerownia_Ruch
      description: ''
      use_blueprint:
        path: homeassistant/motion_light.yaml
        input:
          motion_entity: binary_sensor.ikea_of_sweden_tradfri_motion_sensor_ruch
          light_target:
            entity_id: light.boneio_32_l_06_76f0b4_light_16
    - id: '1713885217809'
      alias: zamknijWszystkoNaNoc
      description: zamyka wszystkie rolety jeśli wszystkie klamki i zamki są zamknięte
      trigger:
      - platform: sun
        event: sunset
        offset: 00:30:00
      condition:
      - condition: state
        entity_id: binary_sensor.boneio_c_07_21a5c4_in_28
        state: 'off'
      - condition: state
        entity_id: binary_sensor.boneio_c_07_21a5c4_in_26
        state: 'off'
      - condition: state
        entity_id: binary_sensor.boneio_c_07_21a5c4_in_29
        state: 'off'
      - condition: state
        entity_id: binary_sensor.boneio_c_07_21a5c4_in_33
        state: 'off'
      - condition: state
        entity_id: binary_sensor.boneio_c_07_21a5c4_in_25
        state: 'off'
      - condition: state
        entity_id: binary_sensor.boneio_c_07_21a5c4_in_35
        state: 'off'
      - condition: state
        entity_id: binary_sensor.boneio_c_07_21a5c4_in_31
        state: 'off'
      - condition: state
        entity_id: lock.boneio_c_07_21a5c4_drzwi
        state: locked
      action:
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: cb6eed106dc75726637f7e685d49d689
        type: close
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: 1876ab62f344e8d638b28606ce0d2ee9
        type: close
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: a5a11ee8d63d9d1726e720383da22140
        type: close
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: 4924564fbf13a69fa0873e66c9d3a863
        type: close
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: 326374d57a47a388b91ecae0c1b3745a
        type: close
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: 3aa3e0358897dc25edadde10d0a430ba
        type: close
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: 4d4b162dbc7cd3aeb917ede1a0984a7b
        type: close
      - device_id: cf8f38db88ccd8bf86ebe9efd41b9b58
        domain: cover
        entity_id: e9dde732bd25d829fe3a86a4eb6ec81d
        type: close
      mode: single
    - id: '1714469574083'
    alias: Dzwonek_new
    description: ''
    trigger:
    - device_id: 2e953f3699b8e166c5c96b31c076115e
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: turn_on
    condition: []
    action:
    - service: media_player.play_media
      target:
        entity_id: media_player.sonos_roam
      data:
        media_content_id: media-source://media_source/media/media/Ding-dong.wav
        media_content_type: audio/x-wav
      metadata:
        title: Ding-dong.wav
        thumbnail:
        media_class: music
        children_media_class:
        navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://media_source
        - media_content_type: ''
          media_content_id: media-source://media_source/media/media
    mode: single
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    customize: !include customize.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
