apiVersion: v1
data:
  configuration.yaml: |2-


    # Let new devices join our zigbee network
    permit_join: true
    # Home Assistant integration (MQTT discovery)
    homeassistant: true
    # Docker-Compose makes the MQTT-Server available using "mqtt" hostname
    # MQTT server URL
    mqtt:
      base_topic: homeassistant
      server: "mqtt://10.0.50.11:31883" # mqtt://<name_of_pod>.<name_of_namespace> (mosquitto)
    # Zigbee Adapter path
    serial:
      port: tcp://10.0.50.5:6638
    # Enable the Zigbee2MQTT frontend
    frontend:
      port: 8080
    # Let Zigbee2MQTT generate a new network key on first start
    advanced:
      homeassistant_legacy_entity_attributes: false
      legacy_api: false
      legacy_availability_payload: false
      #network_key: GENERATE
      #log_output: ["console"]
      log_level: debug
      log_output:
      - console
      - file
    device_options:
      legacy: false
    ## Map devices to persistent /data directory
    devices: /data/devices.yaml
    groups: /data/groups.yaml
    ota:
      ikea_ota_use_test_url: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"configuration.yaml":"\n# Let new devices join our zigbee network\npermit_join: true\n# Home Assistant integration (MQTT discovery)\nhomeassistant: true\n# Docker-Compose makes the MQTT-Server available using \"mqtt\" hostname\n# MQTT server URL\nmqtt:\n  base_topic: homeassistant\n  server: \"mqtt://10.0.50.11:31883\" # mqtt://\u003cname_of_pod\u003e.\u003cname_of_namespace\u003e (mosquitto)\n# Zigbee Adapter path\nserial:\n  port: tcp://10.0.50.5:6638\n# Enable the Zigbee2MQTT frontend\nfrontend:\n  port: 8080\n# Let Zigbee2MQTT generate a new network key on first start\nadvanced:\n  homeassistant_legacy_entity_attributes: false\n  legacy_api: false\n  legacy_availability_payload: false\n  #network_key: GENERATE\n  #log_output: [\"console\"]\n  log_level: debug\n  log_output:\n  - console\n  - file\ndevice_options:\n  legacy: false\n## Map devices to persistent /data directory\ndevices: /data/devices.yaml\ngroups: /data/groups.yaml"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"z2mqtt"},"name":"z2mqtt-config","namespace":"home-assistant"}}
  creationTimestamp: "2024-01-08T08:20:48Z"
  labels:
    app: z2mqtt
  name: z2mqtt-config
  namespace: home-assistant
  resourceVersion: "1066111"
  uid: e23373cb-f673-4d0f-b398-5c75884f7200
