---
apiVersion: v1
kind: Service
metadata:
  namespace: ha
  name: z2mqtt-02
spec:
  selector:
    app: z2mqtt-02
  type: LoadBalancer
  loadBalancerIP: 10.0.51.105
  ports:
    - name: z2mqtt-02
      port: 8082
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2mqtt-02-vol01
  namespace: ha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: z2mqtt-02-ingress
  namespace: ha
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
    - host: z2mqtt-02.48340.xyz
      http:
        paths:
          - backend:
              service:
                port:
                  number: 8082
                name: z2mqtt-02
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - z2mqtt-02.48340.xyz
      secretName: z2mqtt-02-tls
  ingressClassName: traefik
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ha
  name: z2mqtt-02
  labels:
    app: z2mqtt-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2mqtt-02
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: z2mqtt-02
    spec:
      hostNetwork: true
      containers:
      - name: z2mqtt-02
        #image: alpine:latest
        #command:
        #  - /bin/sh
        #  - "-c"
        #  - "sleep 60m"
        image: koenkk/zigbee2mqtt:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"            
        env:
          - name: TZ
            value: Europe/Warsaw
          - name: "ZIGBEE2MQTT_DATA"
            value: "/app/data"
          - name: "ZIGBEE2MQTT_CONFIG_MQTT_SERVER"
            value: "mqtt://10.0.50.12:31883"
          - name: "ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC"
            value:  "zigbee2mqtt-02"
          - name: "ZIGBEE2MQTT_CONFIG_HOMEASSISTANT"
            value:  "true"            
          - name: "ZIGBEE2MQTT_CONFIG_PERMIT_JOIN"
            value:  "true"
          - name: "ZIGBEE2MQTT_CONFIG_SERIAL_PORT"
            value:  "tcp://10.0.50.4:6638"
          - name: "ZIGBEE2MQTT_CONFIG_SERIAL_RTSCTS"
            value:  "false"
          - name: "ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE"
            value:  "115200"                        
          - name: "ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER"
            value:  "ember"
          - name: "ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED"
            value:  "false"
          - name: "ZIGBEE2MQTT_CONFIG_FRONTEND"
            value:  "false"
          - name: "ZIGBEE2MQTT_CONFIG_FRONTEND_PORT"
            value:  "8080"
          # - name: "ZIGBEE2MQTT_CONFIG_DEVICES"
          #   value:  '/app/data/devices.yaml'                      
          # - name: "ZIGBEE2MQTT_CONFIG_GROUPS"
          #   value:  "/app/data/groups.yaml"
          - name: "ZIGBEE2MQTT_CONFIG_OTA_IKEA_OTA_USE_TEST_URL"
            value:  "true"
          - name: "ZIGBEE2MQTT_DEVICE_OPTIONS_LEGACY"
            value: "false"
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID" 
            value: "10841"
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID"
            value:  '[177,236,227,102,233,177,36,68]'
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY"
            value:  '[1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]'
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL"
            value:  "26"
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER"
            value:  "20"                        
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES"
            value:  "false"
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API"
            value:  "false" 
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD"
            value:  "false"
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL"
            value:  "debug"                        
          - name: "ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT"
            value:  '["console","file"]'     
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: z2mqtt-02-volume
          mountPath: /app/data
        # - name: z2mqtt-02-config
        #   mountPath: /app/data/configuration.yaml
        #   subPath: configuration.yaml
        # - name: gfs-z2mqtt-02-volume
        #   mountPath: /app/data/devices_rw.yaml
        # - name: z2mqtt-02-config
        #   mountPath: /app/data/devices.yaml
        # subPath: devices.yaml 
        - name: z2mqtt-02-udev
          mountPath: /run/udev
        # - mountPath: /dev/ttyACM0
        #   name: cc2351
        # securityContext:
        #   privileged: true
      hostNetwork: true
      volumes:
        - name: z2mqtt-02-volume
          persistentVolumeClaim:
            claimName: z2mqtt-02-vol01
        - name: z2mqtt-02-udev
          hostPath:
            path: /run/udev
        # - name: cc2351
        #   hostPath:
        #     path: /dev/ttyACM0
        # - name: z2mqtt-02-config
        #   configMap:
        #     name: z2mqtt-02-config
      