---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: z2mqtt2
spec:
  selector:
    app: z2mqtt2
  type: LoadBalancer
  ports:
    - name: z2mqtt2
      port: 8888
      # targetPort: 8888
      # nodePort: 31888
      # protocol: TCP
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: gfs-z2mqtt2-local-volume
#   namespace: home-assistant
# spec:
#   storageClassName: longhorn
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/data/zigbee2"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: home-assistant
#   name: gfs-z2mqtt2-volume-claim
#   labels:
#     app: z2mqtt2
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 500Mi
# ---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gfs-z2mqtt2-volume-claim
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: z2mqtt2
  labels:
    app: z2mqtt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2mqtt2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: z2mqtt2
    spec:
      hostNetwork: true
      containers:
      - name: z2mqtt2
        image: koenkk/zigbee2mqtt:latest
        imagePullPolicy: Always
        env:
          - name: TZ
            value: Europe/Warsaw
          - name: "ZIGBEE2MQTT_DATA"
            value: "/app/data"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER # optional - can also be configured in the configuration.yaml in the configmap
            value: "mqtt://10.0.50.11:31883"
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        volumeMounts:
        - name: gfs-z2mqtt2-volume
          mountPath: /app/data
        - name: z2mqtt2-config
          mountPath: /app/data/configuration.yaml
          subPath: configuration.yaml
        - name: z2mqtt2-udev
          mountPath: /run/udev
      volumes:
      - name: gfs-z2mqtt2-volume
        persistentVolumeClaim:
          claimName: gfs-z2mqtt2-volume-claim
      - name: z2mqtt2-udev
        hostPath:
          path: /run/udev
      # - name: cc2351
      #   hostPath:
      #     path: /dev/ttyACM0
      - name: z2mqtt2-config
        configMap:
          name: z2mqtt2-config
  