#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: home-assistant
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: z2mqtt2-config
  namespace: home-assistant
  labels:
    app: z2mqtt2
data:
  configuration.yaml: |-

    # Let new devices join our zigbee network
    permit_join: true
    # Home Assistant integration (MQTT discovery)
    homeassistant: true
    # Docker-Compose makes the MQTT-Server available using "mqtt" hostname
    # MQTT server URL
    mqtt:
      #base_topic: homeassistant
      # server: "mqtt://10.0.50.11:31883" # mqtt://<name_of_pod>.<name_of_namespace> (mosquitto)
      server: "mqtt://mqtt.home-assistant:31883"
      base_topic: zigbee2mqtt2
    # Zigbee Adapter path
    serial:
      # port: tcp://10.0.50.4:6638
      # Location of SLZB-06M
      port: tcp://10.0.50.4:6638
      baudrate: 115200
      adapter: ezsp
    # Disable green led?
      disable_led: false
    
    # Enable the Zigbee2MQTT frontend
    frontend:
      port: 8888
    # Let Zigbee2MQTT generate a new network key on first start
    advanced:
    # Set output power to max 20
      transmit_power: 20
    # 
      homeassistant_legacy_entity_attributes: false
      legacy_api: false
      legacy_availability_payload: false
      #network_key: GENERATE
      #log_output: ["console"]
      log_level: debug
      log_output:
      - console
      - file
    device_options:
      legacy: false
    ota:
      ikea_ota_use_test_url: true
    ## Map devices to persistent /data directory
    devices: /app/data/devices.yaml 

    groups: /app/data/groups.yaml
  
  # devices.yaml: |
  #   '0x842e14fffe15569e':
  #     friendly_name: 'OnOff_01'