#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: home-assistant
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: z2mqtt-config
  namespace: home-assistant
  labels:
    app: z2mqtt
data:
  configuration.yaml: |-

    # Let new devices join our zigbee network
    permit_join: true
    # Home Assistant integration (MQTT discovery)
    homeassistant: true
    # Docker-Compose makes the MQTT-Server available using "mqtt" hostname
    # MQTT server URL
    mqtt:
      #base_topic: homeassistant
      server: "mqtt://10.0.50.11:31883" # mqtt://<name_of_pod>.<name_of_namespace> (mosquitto)
    # Zigbee Adapter path
    serial:
      port: tcp://10.0.50.5:6638
    # Enable the Zigbee2MQTT frontend
    frontend:
      port: 8888
    # Let Zigbee2MQTT generate a new network key on first start
    advanced:
      # Optional: ZigBee pan ID (default: shown below)
      # Setting pan_id: GENERATE will make Zigbee2MQTT generate a new panID on next startup
      pan_id: 0x1a62
      #pan_id: GENERATE
      # Optional: Zigbee extended pan ID, GENERATE will make Zigbee2MQTT generate a new extended panID on next startup (default: shown below)
      ext_pan_id: [0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]
      #ext_pan_id: GENERATE
      network_key: '!secret.yaml network_key' 
      channel: 15
      transmit_power: 20
      homeassistant_legacy_entity_attributes: false
      legacy_api: false
      legacy_availability_payload: false
      #network_key: GENERATE
      #log_output: ["console"]
      log_level: debug
      log_output:
      - console
      - file
    device_options:
      legacy: false
    ota:
      ikea_ota_use_test_url: true
    environment:
        - TZ=Europe/Warsaw
    ## Map devices to persistent /data directory
    devices: /app/data/devices.yaml 

    groups: /app/data/groups.yaml
  
  # devices.yaml: |
  #   '0x842e14fffe15569e':
  #     friendly_name: 'OnOff_01'
  secret.yaml: |-
    network_key: [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]