---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: z2mqtt
spec:
  selector:
    app: z2mqtt
  type: NodePort
  ports:
    - name: z2mqtt
      port: 8080
      targetPort: 8080
      nodePort: 31080
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-z2mqtt-local-volume
  namespace: home-assistant
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/zigbee"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home-assistant
  name: gfs-z2mqtt-volume-claim
  labels:
    app: z2mqtt
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: z2mqtt
  labels:
    app: z2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: z2mqtt
    spec:
      containers:
      - name: z2mqtt
        #image: alpine:latest
        #command:
        #  - /bin/sh
        #  - "-c"
        #  - "sleep 60m"
        image: koenkk/zigbee2mqtt:latest
        imagePullPolicy: Always
        env:
          - name: TZ
            value: Europe/Warsaw
          - name: "ZIGBEE2MQTT_DATA"
            value: "/app"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER # optional - can also be configured in the configuration.yaml in the configmap
            value: "mqtt://10.0.50.11:31883"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: gfs-z2mqtt-volume
          mountPath: /data
        - name: z2mqtt-config
          mountPath: /app/configuration.yaml
          subPath: configuration.yaml
        - name: z2mqtt-config
          mountPath: /app/devices.yaml
          subPath: devices.yaml 
        - name: z2mqtt-udev
          mountPath: /run/udev
        # - mountPath: /dev/ttyACM0
        #   name: cc2351
        # securityContext:
        #   privileged: true
      hostNetwork: true
      volumes:
        - name: gfs-z2mqtt-volume
          persistentVolumeClaim:
            claimName: gfs-z2mqtt-volume-claim
        - name: z2mqtt-udev
          hostPath:
            path: /run/udev
        # - name: cc2351
        #   hostPath:
        #     path: /dev/ttyACM0
        - name: z2mqtt-config
          configMap:
            name: z2mqtt-config
      