---
- packages:
    - bash-completion
    - git
    - apt-transport-https
    - ca-certificates
    - wget
    - curl
    - software-properties-common
    - gnupg2
    - mc
    - rsync
    - nmap
    - tcpdump
    - dnsutils
    - inetutils-ping
    - python3-pip
    - byobu
    - wget
    - curl
    - vim
    - sshpass
    - glusterfs-server
    - glusterfs-cli
    - docker-ce
    - docker-ce-cli
    - containerd.io